{{- if .Values.ingress.enabled }}
{{- if eq .Values.service.type "ClusterIP" }}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ template "fullname" . }} 
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }} 

spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }} 
          servicePort: {{ .Values.service.internal_port }} 
{{- end }}
{{- end }}
