apiVersion: v1
kind: Secret

metadata:
  name: {{ template "fullname" . }}-registrykey
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/service-account.name: {{ template "fullname" . }} 

type: kubernetes.io/dockerconfig
data:
  .dockercfg: "{{ .Values.dockercfg }}" 
